# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
builds:
  - binary: nitro
    main: ./cmd/nitro/main.go
    id: nitro
    goos:
      - linux
      - windows
    goarch:
      - amd64
  - binary: nitro
    main: ./cmd/nitro/main.go
    id: nitro-macos
    goos:
      - darwin
    goarch:
      - amd64
signs:
  - signature: "${artifact}.dmg"
    ids:
      - nitro-macos
    cmd: gon
    # you can follow the gon docs to properly create the gon.hcl config file:
    # https://github.com/mitchellh/gon
    args:
      - gon.hcl
    artifacts: all
archives:
  - replacements:
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
