#cloud-config
runcmd:
  - sudo add-apt-repository -y ppa:nginx/stable
  - sudo add-apt-repository -y ppa:ondrej/php
packages:
  - curl
  - wget
  - zip
  - unzip
  - git
  - openssl
write_files:
  - content: |
      server {
          listen 80 default_server;

          root CHANGEPATH;

          index index.html index.htm index.php;

          server_name CHANGESERVERNAME;

          location / {
              try_files $uri $uri/ /index.php$is_args$args;
          }

          location ~ \.php$ {
             include snippets/fastcgi-php.conf;
             fastcgi_pass unix:/var/run/php/phpCHANGEPHPVERSION-fpm.sock;
          }
      }
    path: /etc/phpdev/templates/nginx_site.conf
  - content: |
      #!/bin/bash
      SITE="$1"
      PATH="$2"

      add_nginx_site() {
        // check the number of args
        // get the name of the site
        // get the path to index.php
        // get the php version
        // cp /etc/phpdev/templates/nginx_site.conf /etc/nginx/sites-available/$1.conf
        // sed servername
        // sed phpversion
        // sed pathtoindex.php
        echo "created new site $SITE at $PATH"
      }
    path: /usr/sbin/add-nginx-site
    permissions: '+770'
