#cloud-config
packages:
  - redis
write_files:
  # create the main bootstrap script
  - path: /etc/nitro/bootstrap.sh
    content: |
      #!/bin/bash

      # TODO allow passing args for the bootstrap script for
      # phpversion="$1"
      # database="$2"

      # install php 7.4
      sudo bash /etc/nitro/php/php-74.sh

      # install nginx
      sudo bash /etc/nitro/nginx/install.sh

      # install mariadb
      sudo bash /etc/nitro/mariadb/install.sh

      # run the mariadb setup
      sudo bash /etc/nitro/mariadb/setup.sh
    permissions: '770'
  # create the php install scripts
  - path: /etc/nitro/php/php-74.sh
    content: |
      #!/bin/bash
      apt install -y php7.4 php7.4-mbstring php7.4-cli php7.4-curl php7.4-fpm php7.4-gd php7.4-intl php7.4-json \
      php7.4-mysql php7.4-opcache php7.4-pgsql php7.4-zip php7.4-xml
  # create the composer install script
  - path: /etc/nitro/composer-install.sh
    content: |
      # install composer
      php -r "readfile('http://getcomposer.org/installer');" | sudo php -- --install-dir=/usr/bin/ --filename=composer
    permissions: '770'
  # create mariadb scripts
  - path: /etc/nitro/mariadb/setup.sh
    content: |
      # remove bind from mariadb to allow remote connection
      systemctl stop mariadb
      sed -i 's|bind-address|#bind-address|g' /etc/mysql/mariadb.conf.d/50-server.cnf
      systemctl start mariadb

      # create the database and user
      export USER_PASS=$(openssl rand -base64 16)
      echo "$USER_PASS" > /etc/nitro/.mysql_password
      export MYSQL_USER=$(cat /etc/nitro/.mysql_password)

      sudo sed -i 's|CHANGEME|'$MYSQL_USER'|g' /etc/nitro/mariadb/init.sql

      sudo mysql -u root < /etc/nitro/mariadb/init.sql
    permissions: '770'
  - path: /etc/nitro/mariadb/install.sh
    content: |
      #!/bin/bash
      apt install -y mariadb-server
  - path: /etc/nitro/mariadb/init.sql
    content: |
      CREATE DATABASE IF NOT EXISTS craftcms;
      CREATE USER IF NOT EXISTS 'craftcms'@'%' IDENTIFIED BY 'CHANGEME';
      GRANT CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT ON `craftcms`.* TO 'craftcms'@'%';
      FLUSH PRIVILEGES;
    permissions: '770'
  # create nginx install scripts
  - path: /etc/nitro/nginx/install.sh
    content: |
      #!/bin/bash
      apt install -y nginx
  - path: /etc/nitro/nginx/template.conf
    content: |
      server {
          listen 80 default_server;

          root CHANGEPATH;

          index index.html index.htm index.php;

          server_name CHANGESERVERNAME;

          location / {
              try_files $uri $uri/ /index.php$is_args$args;
          }

          location ~ \.php$ {
             include snippets/fastcgi-php.conf;
             fastcgi_pass unix:/var/run/php/phpCHANGEPHPVERSION-fpm.sock;
          }
      }
    permissions: '770'
runcmd:
  - sudo add-apt-repository -y ppa:nginx/stable
  - sudo add-apt-repository -y ppa:ondrej/php
  - sudo apt update -y
  - sudo apt upgrade -y
