#cloud-config
runcmd:
  - sudo add-apt-repository -y ppa:nginx/stable
  - sudo add-apt-repository -y ppa:ondrej/php
  - sudo apt-get update -y
packages:
  - htop
  - tmux
  - curl
  - wget
  - zip
  - unzip
  - git
  - vim
  - openssl
